### PR TITLE
Update README.md

### LINKED ISSUE #97: [Docs]: Tidy up README
Recommended doc changes

- Indent Markdown and YAML inside bullet points.
- Convert bullet points to numbered points - steps are meant to be followed in order so numbering is important.
- Headings started at H3 `###`, so made H3 into H2 and H4 into H3 to follow a more typical approach to structuring a Markdown doc or webpage.
- Add whitespace in the dense Markdown, like around headings.
- Added some whitespace and name fields to the YAML.
- Changed id to ID

### PR DESCRIPTION
**Pull request by MichaelCurrin**
Fixes #97

### CODE REVIEW

**Comment by MichaelCurrin** [comment]
Idea for future - instead of referencing some user content URL for images, which are separate from the repo, rather put them in the repo.

e.g. Upload `sample.png` to your repo.

Then reference as

```html
<img src="sample.png">
```

**Comment by gautamkrishnar** [comment]
> Idea for future - instead of referencing some user content URL for images, which are separate from the repo, rather put them in the repo.
> 
> e.g. Upload `sample.png` to your repo.
> 
> Then reference as
> 
> ```
> 
> ```

Thanks for the suggestion. I generally don't want the repo to be bloated with images so that it will introduce unnecessary bytes to the repo size while cloning. That's the main reason I used the GitHub CDN instead.

**Review by gautamkrishnar — APPROVED** [review]

**Comment by gautamkrishnar** [comment]
@MichaelCurrin thanks a lot for contributing 👍🏻  🎖️

**Comment by MichaelCurrin** [comment]
Oh right thanks for the info. If speed/size is your concern and no one else needs to edit the image, then CDN is fine.

**Comment by gautamkrishnar** [comment]
@MichaelCurrin anyone can also upload images, Just use #1 issue to upload and use the url.

**Pull request merged**
