### PR TITLE
Adding the possibility to ad an accept header to the request

### LINKED ISSUE #19: [Bug]: Response 406 when asking for rss stream
**Describe the bug**
When I use the provided configuration and the cronjob runs I get a `406 Not Acceptable` response in the github action as an error.

**To Reproduce**
1. Implement Github Action as described
2. Let the job run with `feed_list: "https://offeringsolutions.azurewebsites.net/index.xml"` or `"https://offering.solutions/index.xml"`
3. See the 406 Error

```
Run gautamkrishnar/blog-post-workflow@master
  with:
    feed_list: https://offeringsolutions.azurewebsites.net/index.xml
    gh_token: ***
    readme_path: ./README.md
    max_post_count: 5
    disable_sort: false
    filter_comments: medium,stackoverflow/Comment by $author/,stackexchange/Comment by $author/
    template: default
    commit_message: Updated with the latest blog posts
    committer_username: blog-post-bot
    committer_email: blog-post-bot@example.com
##[error]https://offeringsolutions.azurewebsites.net/index.xml runner failed, please verify the configuration. Error:
##[error]Error: Status code 406
0 blog posts fetched
```

**Expected behavior**
I would hav eexpected to read the xml and show the latest blogposts.

**Screenshots**
None

**Additional context**
`"https://offering.solutions/index.xml"` is running behind cloudflare, `"https://offeringsolutions.azurewebsites.net/index.xml"` is not, both of them return a 406

### PR DESCRIPTION
**Pull request by FabianGosebrink**
trying to fix fixes #19

### CODE REVIEW

**Comment by gautamkrishnar** [comment]
@FabianGosebrink sorry I had already started working on this one 😄 thanks for the PR, can you please revert the changes on the package.lock.json?

**Comment by gautamkrishnar** [comment]
@FabianGosebrink I will do that. Thanks. 😄

**Comment by FabianGosebrink** [comment]
Alright, you got this. thanks, but setting the accept header AND the user_agent solves it for me. Thanks for your time and effort!

**Comment by gautamkrishnar** [comment]
@FabianGosebrink will release this soon, need to fix the GitHub workflow to build this action.

**Comment by FabianGosebrink** [comment]
Easy, no rush. Thanks for your time!

**Pull request merged**
